[server]
listenAddr="0.0.0.0"
port="8000"
readTimeout=150
writeTimeout=150
closeTimeout=150

[database]
host=""
port=""
username=""
password=""
sslMode=""
name=""

[token]
jwtSignKey=""

[app]
limit=20

